### PR TITLE
add --commitment-interval argument

### PR DESCRIPTION
**Pull request by couillardcharles**

### CODE REVIEW

**Comment by petertodd** [comment]
Sorry, but I'm not sure I can merge this easily, as I'm frankly not sure how much stuff in the OTS ecosystem that makes assumptions about the commit interval.

FWIW do you need a longer or shorter commitment interval?

**Comment by couillardcharles** [comment]
Hi Peter,

Thanks for your answer.

The idea was to use a shorter interval to decrease latency on timestamp requests.

**Comment by petertodd** [comment]
Heh, I was worried you'd say that. :)

Sorry, but I'm pretty sure that will break things right now. OTOH, it's a reasonable request so I'd like to be able to support it.

Been awhile since I've looked into that code in detail; does it seem to work on your end? I'd be happy merging it with a loud "EXPERIMENTAL" warning on the flag.

**Comment by couillardcharles** [comment]
Yeah, it seems to work, simple test done on regtest :
- interval at 0.1 sec
- 10 sequential stamp calls (approx 200-250ms per call)
- verify ok (pending confirm)
- timestamp tx created
- upgrade ok
- verify ok

**Comment by petertodd** [comment]
Just a quick ping: mind adding "EXPERIMENTAL" to the help text? I'll merge this once that's done.

**Comment by couillardcharles** [comment]
Hi,
I'm not sure it's a good idea to merge this PR.
It's linked to my "master" branch, and I updated it with another interval configuration: the stamper one.

I would like to decrease latency between a post of a new timestamp and the ability to check an ots proof. In the current implementation, there are 2 intervals of 1 second used: in the Aggregator and in the Stamper. It works pretty well by specifying interval < 1 second (100 ms for example). 

I can add the EXPERIMENTAL text on the 2 new params if you think it's ok.

But it's not really my main issue ;) I try to find a way to be sure that a timestamp is available as pending to allow third parties to check ots proofs.
I found a [FIXME](https://github.com/opentimestamps/opentimestamps-server/blob/master/otsserver/rpc.py#L124) in the code that describes my issue: "stamper may return `Not Found` for a commitment that was just added, as commitments aren't actually added directly to the pending data structure, but rather, added to the journal and only then added to pending".
I'm not able to fix this limitation, so intervals configuration is more a hack than a fix.

**Comment by petertodd** [comment]
Ah! I remember that one. IIRC there's no easy fix for that as the stamper and the calendar servers may not even be the same computer, and thus there's no way for them to be in consensus about the existence of a pending commitment. I'd suggest you find a way to fix that in your application instead.

Note that right now, as an example, the bob calendar is served by Amazon Cloudfront, so there's an entire layer of complex caching that happens, and each request to the "bob calendar" could go to a set of hundreds of different physical computers that I have no real control over beyond cache expiration tags. It's very important that running calendars be simple and cheap, so I really don't want to give more guarantees in the API than I have too.

**Comment by petertodd** [comment]
Closing, because as mentioned above doesn't look like we can add this in this way.

**Pull request closed without merging**
